solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, uma_crianca, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, duas_criancas, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, nenhum_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).

solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, nenhuma_crianca, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, uma_crianca, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, duas_criancas, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, um_adulto, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).

solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).

solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, nenhuma_crianca, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, uma_crianca, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, duas_criancas, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, nenhuma_cama, [casa1]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, uma_cama, [casa2]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, duas_camas, [casa3]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, tres_camas, [casa4]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, um_quarto, mais_de_3_camas, [casa5]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, nenhuma_cama, [casa6]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, uma_cama, [casa7]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, duas_camas, [casa8]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, tres_camas, [casa9]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, dois_quartos, mais_de_3_camas, [casa10]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, nenhuma_cama, [casa11]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, uma_cama, [casa12]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, duas_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, tres_camas, [casa13]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, tres_quartos, mais_de_3_camas, [casa15]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, nenhuma_cama, [casa16]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, uma_cama, [casa17]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, duas_camas, [casa18]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, tres_camas, [casa19]).
solucao('Apartamento S.Victor', estadia_longa, mais_quinhentos_euros, mais_de_dois_adultos, mais_de_duas_criancas, nao_tem_animal, quatro_quartos, mais_de_3_camas, [casa20]).
